### ISSUE TITLE
Having Trouble. It works but get these errors:

### ISSUE THREAD

**Issue by Carreiroa** [kurocode25/mdforvim#4]
![image](https://user-images.githubusercontent.com/77595798/139478109-211b1b30-75ce-4d9f-821e-2eff61d2f363.png)

I'm not sure what else is required. Also, it appears only to work with the .mkd file extension and not .md -- not a huge issue, but wondering if the problem is related.

**Comment by kurocode25** [comment]
Thank you for report. I survey cause of error. Please wait for a little while longer.

**Comment by kurocode25** [comment]
I fixed bug. This trouble caused by variable definition.
Thank you for your report.

**Comment by Carreiroa** [comment]
No problem. Glad to help. I'm still new to a lot of things here. Learning as I go. All the best.
